
namespace Monitor.Application.MonitoringChecks.Models
{
    public enum CheckTypeEnum
    {
        HomePageAvailableProd = 1,
        CategoryMetaTagsProd = 2,
        WebUISearchProd = 3,
        ApiSearchProd = 4,
        HomePageAvailableBeta = 5,
        CategoryMetaTagsBeta = 6,
        WebUISearchBeta = 7,
        ApiSearchCheckProd = 8,
        ApiSearchCheckBeta = 9,
        ExampleUnitTestCheckProd = 10,
        LoginUnitTestProd = 11,
        LoginAdminPanelUnitTestProd = 12,
        CategoryHtmlCheckProd = 13,
        CategoryHtmlCheckBeta = 14,
        ProductHtmlCheckProd = 15,
        ProductHtmlCheckBeta = 16,
        ProductMetaTagsProd = 17,
        ProductMetaTagsBeta = 18,
        ApiAreasCheckProd = 19,
        ApiAreasCheckBeta = 20,
        ApiNPSettlementsProd = 21,
        ApiNPSettlementsBeta = 22,
        ApiNovaPoshtaPointsProd = 23,
        ApiNovaPoshtaPointsBeta = 24,
        VsTestExampleBeta = 25,
        ApiDeliveryAutoSettlementsProd = 26,
        ApiDeliveryAutoSettlementsBeta = 27,
        ApiDeliveryAutoPointsProd = 28,
        ApiDeliveryAutoPointsBeta = 29,
        ApiUkrPoshtaSettlementsProd = 30,
        ApiUkrPoshtaSettlementsBeta = 31,
        ApiUkrPoshtaPointsProd = 32,
        ApiUkrPoshtaPointsBeta = 33,
        ApiStoAutodocSettlementsProd = 34,
        ApStoAutodocSettlementsBeta = 35,
        ApiStoAutodocPointsProd = 36,
        ApiStoAutodocPointsBeta = 37,
        HtmlDesktopProd = 38,
        HtmlDesktopBeta = 39,
        HtmlMobileProd = 40,
        HtmlMobileBeta = 41,
        FeedChekPriceProd = 42,
        FeedChekGoogleProd = 43,
        FeedChekFacebookProd = 44,
        FeedChekPromProd=45,
        FeedChekCategoriesProd = 46,


    }
}
