// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitor.Persistence.Dashboard;

namespace Monitor.Persistence.Migrations
{
    [DbContext(typeof(DashboardContext))]
    [Migration("20191106161936_CreateDashboardDB")]
    partial class CreateDashboardDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Monitor.Persistence.Dashboard.Models.EFMontlySalesInfoModel", b =>
                {
                    b.Property<short>("Year");

                    b.Property<short>("Month");

                    b.Property<decimal>("ActualSalesSumm");

                    b.Property<decimal>("PlannedSalesSumm");

                    b.HasKey("Year", "Month");

                    b.ToTable("MontlySalesInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
